name: "Play Store"

on:
  workflow_call:
    secrets:
      ANDROID_STOREPASSWORD:
        required: true
      ANDROID_KEYSTORE:
        required: true

jobs:
  build-android:
    name: "Publish to Play Store"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.29.1'
          channel: 'stable'
          cache: true
      - name: Clean Flutter
        run: flutter clean
      - name: Install dependencies
        run: flutter pub get

      - name: Generate keyproperties
        run: |
          cd android
          touch key.properties
          echo "storePassword=${{ secrets.ANDROID_STOREPASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.ANDROID_STOREPASSWORD }}" >> key.properties
          echo "keyAlias=upload" >> key.properties
          echo "storeFile=./keystore.jks" >> key.properties

      - name: Generate keystore
        env: 
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: echo "$ANDROID_KEYSTORE" | base64 -d >> ./android/app/keystore.jks

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release 
      - name: Build App Bundle
        run: flutter build appbundle --release 

      - name: Upload Artifact APk
        uses: actions/upload-artifact@main
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifact AAB
        uses: actions/upload-artifact@main
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab